# Generated by Django 4.2.7 on 2023-11-28 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("achievements", "0001_initial"),
        ("notes", "0001_initial"),
        ("feed", "0001_initial"),
        ("advertisements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="noteevent",
            name="note",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="note_events",
                to="notes.note",
            ),
        ),
        migrations.AddField(
            model_name="advertisementevent",
            name="advertisement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="advertisement_events",
                to="advertisements.advertisement",
            ),
        ),
        migrations.AddField(
            model_name="achievementevent",
            name="achievement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="achievement_events",
                to="achievements.userachievement",
            ),
        ),
    ]
